<?php

/**
 * Implements hook_menu().
 */
function modalform_menu() {
  $items = array();
 
  $items['modalform/page'] = array(
    'page callback' => 'modalform_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
 
  $items['modalform/%ctools_js'] = array(
    'page callback' => 'modalform_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
 
  return $items;
}

/**
 * An example page.
 */
function modalform_page() {
  // Load the modal library and add the modal javascript.
  ctools_include('modal');
  ctools_modal_add_js();
  return _modalform_make_link('Magical modal');
}

/**
 * Ajax menu callback.
 */
function modalform_callback($ajax) {

  if ($ajax) {
  
    ctools_include('ajax');
    ctools_include('modal');
 
    $form_state = array(
      'ajax' => TRUE,
      'title' => t('modalform Modal Form'),
    );
 
    // Use ctools to generate ajax instructions for the browser to create
    // a form in a modal popup.
    $output = ctools_modal_form_wrapper('modalform_form', $form_state);
 
    // If the form has been submitted, there may be additional instructions
    // such as dismissing the modal popup.
    if (!empty($form_state['ajax_commands'])) {
      $output = $form_state['ajax_commands'];
    }
 
    // Return the ajax instructions to the browser via ajax_render().
    print ajax_render($output);
    drupal_exit();
  }
  else {
    return drupal_get_form('modalform_form');
  }

}

/**
 * Drupal form to be put in a modal.
 */
function modalform_form($form, $form_state) {
  $form = array();
 
  $form['new_link_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Link text'),
  );
 
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
 
  return $form;
}

/**
 * Drupal form submit handler.
 */
function modalform_form_submit(&$form, &$form_state) {
  // Generate the new link using the submitted text value.
  $link = _modalform_make_link($form_state['values']['new_link_text']);
 
  // Tell the browser to close the modal.
  $form_state['ajax_commands'][] = ctools_modal_command_dismiss();
 
  // Tell the browser to replace the old link with the new one.
  $form_state['ajax_commands'][] = ajax_command_replace('#magical-modal-link', $link);
}

/**
 * Helper function to make a link.
 */
function _modalform_make_link($link_text = '') {

  // Set a default value if no text in supplied.
  if (empty($link_text)) {
    $link_text = 'Magical Modal';
  }
 
  return '<div id="magical-modal-link">' . l($link_text, 'modalform/nojs', array('attributes' => array('class' => 'ctools-use-modal'))) . '</div>';
}

